class Routes{
  static const splashScreen = "/SplashScreen";
  static const loginScreen = "/LoginScreen";
  static const buttonNavigationScreen = "/ButtonNavigationScreen";
  static const statisticsScreen = "/StatisticsScreen";
  static const reseatScreen = "/ReseatScreen";
  static const settingScreen = "/SettingScreen";
  static const electronicInvoiceScreen = "/ElectronicInvoiceScreen";
  // static const printInvoiceScreen = "/PrintInvoiceScreen";
  static const createVisitScreen = "/CreateVisitScreen";
  static const customersScreen = "/CustomersScreen";
  static const addCustomerScreen = "/AddCustomerScreen";
  static const addTransferSectionScreen = "/AddTransferSectionScreen";
  static const transferSectionScreen = "/TransferSectionScreen";
  static const fundListScreen = "/FundListScreen";
  static const visitsCarriedOutScreen = "/VisitsCarriedOutScreen";
  static const salesInvoiceScreen = "/SalesInvoiceScreen";
  static const returnInvoiceScreen = "/ReturnInvoiceScreen";
  static const myRequestsScreen = "/MyRequestsScreen";
  static const addMyRequestScreen = "/AddMyRequestScreen";
  static const addLeaveRequestScreen = "/AddLeaveRequestScreen";
  static const leaveRequestsScreen = "/LeaveRequestsScreen";
  static const allCoursesScreen = "/AllCoursesScreen";
  static const recommendationsFromManagerScreen = "/RecommendationsFromManagerScreen";
  static const visitsListScreen = "/VisitsListScreen";
  static const cashInvoiceScreen = "/CashInvoiceScreen";
  static const createMonthlyPlanScreen = "/CreateMonthlyPlanScreen";
  static const salaryScreen = "/SalaryScreen";
}