abstract class RecommendationsFromManagerState {}

class InitialState extends RecommendationsFromManagerState {}

class OnGetManagerRequestsLoadingState extends RecommendationsFromManagerState {}
class OnGetManagerRequestsErrorState extends RecommendationsFromManagerState {}
class OnGetManagerRequestsSuccessState extends RecommendationsFromManagerState {}
class OnGetManagerRequestsCatchErrorState extends RecommendationsFromManagerState {}
